# -*- mode: ruby -*-
# vi: set ft=ruby :

#
#   Vagrant box used for building debian packages for the PPA.
#
Vagrant.configure("2") do |config|

  # Use Ubuntu 16.04 Xenial as a base box.
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", path: "provision.sh"

  # Sync repository
  config.vm.synced_folder '../..', '/home/ubuntu/yubioath-desktop'

  # Uncomment this to add a USB filter for YubiKeys.
  # This will connect the YubiKey to the VM when re-inserted.
  # This filter usess VirtualBox as provider. 
  # Modify the paramters as needed depending on the device.

  # FILTER_NAME="YubiKey"
  # MANUFACTURER="Yubico"
  # VENDOR_ID="0x1050"
  # PRODUCT_ID="0x0407"
  # PRODUCT="Yubikey 4 OTP+U2F+CCID"

   config.vm.provider "virtualbox" do |vb|
    vb.name = "yubioath-desktop:ppa"
  #  vb.customize ['modifyvm', :id, '--usb', 'on']
  #  vb.customize ['usbfilter', 'add', '0', 
  #    '--target', :id, 
  #    '--name', FILTER_NAME, 
  #   '--manufacturer', MANUFACTURER,
  #    '--vendorid', VENDOR_ID, 
  #    '--productid', PRODUCT_ID, 
  #    '--product', PRODUCT]
   end

end
