#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PATH="${HERE}/usr/bin:${PATH}"
export PYTHONHOME=${HERE}/usr
cd "${HERE}"
exec "${HERE}/usr/bin/yubioath-desktop" "$@"
