name: lint
description: Custom lint rules for Yubico Authenticator

publish_to: none

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer:
  analyzer_plugin:
  collection: ^1.18.0
  custom_lint_builder:
  path: ^1.8.3
