name: lint
description: Custom lint rules for Yubico Authenticator

publish_to: none

version: 1.0.0

environment:
  sdk: ^3.13.0

dependencies:
  analyzer: ^14.4.0
  analysis_server_plugin: ^0.3.23

dev_dependencies:
  analyzer_testing: ^0.4.2
  flutter_lints: ^6.0.0
  test: ^1.32.0
  test_reflective_loader: ^0.4.0
