platform :osx, '10.14'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))

  sign_config_path = File.expand_path(File.join('..', 'Runner', 'Configs', 'Signing-Generated.xcconfig'), __FILE__)
  if ENV['YA_DEV_TEAM']
    File.open(sign_config_path, 'w+') do |file|
      file.write("CODE_SIGN_IDENTITY[sdk=macosx*] = Apple Development\n")
      file.write("DEVELOPMENT_TEAM = #{ENV['YA_DEV_TEAM']}\n")
    end
    puts "Generated sign config: #{sign_config_path}"
  else
    if File.exist?(sign_config_path)
      File.delete(sign_config_path)
      puts "Removed sign config: #{sign_config_path}"
    end
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
