name: Check strings

on: [push, pull_request]

jobs:
  strings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Read variables from repo
      run: cat .github/workflows/env >> $GITHUB_ENV

    - name: Ensure main locale is correct
      run: python check_strings.py lib/l10n/app_en.arb

    - name: Check remaining locales
      run: |
        find lib/l10n/ -name "app_en.arb" -prune -o -name "*.arb" -print0 | xargs -r -n 1 -0 ./check_strings.py >> $GITHUB_STEP_SUMMARY || echo "::warning::Problems in locales"

    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER }}

    - name: Check missing strings
      run: |
        flutter gen-l10n
        if [[ "$(cat missing_l10n_strings.json)" != "{}" ]]; then
                echo "::notice::Strings missing in translations"
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "Missing strings:" >> $GITHUB_STEP_SUMMARY
                cat missing_l10n_strings.json >> $GITHUB_STEP_SUMMARY
        fi
