name: Linux arm64

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: .github/workflows/env

    - name: Read variables from repo
      run: |
        cat .github/workflows/env >> $GITHUB_ENV
        echo CACHE_KEY=${{ runner.os }}-rust-c52f5fc-${{ hashFiles('build-helper.sh', 'helper/**')}} >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq curl libnotify-dev
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Check app versions
      run: |
        python3 set-version.py
        git diff --exit-code

    - name: Check out helper dependencies
      run: |
        git clone --filter=blob:none https://github.com/Yubico/yubikey-manager.git ../yubikit-rs
        git -C ../yubikit-rs checkout c52f5fcdefbb7097f8e036dc022ac33236c3e87a

    - name: Cache helper
      id: cache-helper
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          build/linux/helper
          assets/licenses/helper.txt
        key: ${{ env.CACHE_KEY }}

    - name: Install Rust toolchain
      if: steps.cache-helper.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

    - name: Install cargo-about
      if: steps.cache-helper.outputs.cache-hit != 'true'
      uses: taiki-e/install-action@83ac0ad63c0167e6f06796fab0fce28db1bf3db0 # v2.87.22
      with:
        tool: cargo-about@0.9.2
        fallback: none

    - name: Build the Helper
      if: steps.cache-helper.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -qq libpcsclite-dev libudev-dev libdbus-1-dev build-essential cmake pkg-config libssl-dev
        ./build-helper.sh

    - name: Install Flutter dependencies
      run: |
        sudo apt-get install -qq unzip clang cmake ninja-build pkg-config libgtk-3-dev libx11-dev libxi-dev jq lld

    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        channel: 'main'
        # for weird reasons, arm64 only works on main
        # https://github.com/subosito/flutter-action/issues/268
        flutter-version: ${{ env.FLUTTER }}

    - name: Configure Flutter
      run: |
        git config --global --add safe.directory $FLUTTER_ROOT
        flutter config --enable-linux-desktop
        flutter --version
        flutter pub get

    - name: Run lints/tests
      run: |
        pipx run pre-commit run --all-files
        flutter test

    - name: Build the app
      run: flutter build linux

    - name: Check generated files
      run: git diff --exit-code

    - name: Rename and archive app
      run: |
        export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
        export BASENAME="yubioath-desktop-${REF}-linux-arm64"
        mkdir deploy
        mv build/linux/arm64/release/bundle "build/${BASENAME}"
        tar -czf deploy/${BASENAME}.tar.gz -C build "${BASENAME}"

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: yubioath-desktop-linux-arm64
        path: deploy
