name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Read variables from repo
      run: |
        cat .github/workflows/env >> $GITHUB_ENV
        echo CACHE_KEY=${{ runner.os }}-${{ runner.arch }}-rust-7ba53ca-${{ hashFiles('build-helper.sh', 'helper/**')}} >> $GITHUB_ENV

    - name: Check app versions
      run: |
        python3 set-version.py
        git diff --exit-code

    - name: Set up CocoaPods
      uses: maxim-lobanov/setup-cocoapods@8e97e1e98e6ccf42564fdf5622c8feec74199377 # v1.4.0
      with:
        podfile-path: macos/Podfile.lock

    - name: Check out helper dependencies
      run: |
        git clone --filter=blob:none https://github.com/Yubico/yubikey-manager.git ../yubikit-rs
        git -C ../yubikit-rs checkout 7ba53ca05c8f27b129dfcfa280409d76aa5eaf9c

    - name: Cache helper
      id: cache-helper
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          build/macos/helper
          assets/licenses/helper.txt
        key: ${{ env.CACHE_KEY }}

    - name: Install Rust toolchain
      if: steps.cache-helper.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin

    - name: Install cargo-about
      if: steps.cache-helper.outputs.cache-hit != 'true' && runner.arch == 'ARM64'
      uses: taiki-e/install-action@83ac0ad63c0167e6f06796fab0fce28db1bf3db0 # v2.87.22
      with:
        tool: cargo-about@0.9.2
        fallback: none

    - name: Install cargo-about on Intel
      if: steps.cache-helper.outputs.cache-hit != 'true' && runner.arch == 'X64'
      run: cargo install cargo-about --version 0.9.2 --locked --features cli

    - name: Build the Helper
      if: steps.cache-helper.outputs.cache-hit != 'true'
      run: ./build-helper.sh

    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER }}
        cache: true
        pub-cache: true
    - run: flutter config --enable-macos-desktop
    - run: flutter --version
    - run: flutter pub get

    - name: Build the app
      run: |
        export VERSION_NAME=`./set-version.py | head -n 1 | sed 's/-.*$//g'`
        flutter build macos --build-name=$VERSION_NAME

    - name: Check generated files
      run: git diff --exit-code

    - name: Create dmg
      run: |
        brew install create-dmg
        mkdir source_folder
        cp -R build/macos/Build/Products/Release/"Yubico Authenticator.app" source_folder
        cp resources/icons/dmg-background.png .
        sh create-dmg.sh

    - name: Rename and archive app bundle
      run: |
        export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
        mkdir deploy
        mv yubioath-desktop.dmg deploy
        tar -czf deploy/yubioath-desktop-${REF}.app.tar.gz -C build/macos/Build/Products/Release "Yubico Authenticator.app"
        mv create-dmg.sh deploy
        mv resources/icons/dmg-background.png deploy
        mv macos/helper.entitlements deploy
        mv macos/helper-sandbox.entitlements deploy
        mv macos/Runner/Release.entitlements deploy
        mv macos/release-macos.sh deploy

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: yubioath-desktop-macos
        path: deploy
