name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Read variables from repo
        shell: bash
        run: |
          export $(cat .github/workflows/env)
          cat .github/workflows/env >> $GITHUB_ENV
          echo CACHE_KEY=${{ runner.os }}-py-$PYVER-${{ hashFiles('build-helper.bat', 'helper/**')}} >> $GITHUB_ENV

      - name: Check app versions
        run: |
          python set-version.py
          git diff --exit-code

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYVER }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          enable-cache: true

      - name: Cache helper
        id: cache-helper
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            build/windows/helper
            assets/licenses/helper.json
          key: ${{ env.CACHE_KEY }}

      - name: Build the Helper
        if: steps.cache-helper.outputs.cache-hit != 'true'
        run: .\build-helper.bat

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER }}
      - run: flutter config --enable-windows-desktop
      - run: flutter --version
      - run: flutter pub get

      - name: Run lints/tests
        env:
          SKIP: ${{ steps.cache-helper.outputs.cache-hit == 'true' && 'mypy,ruff check,ruff format' || ''}}
        run: |
          uv tool install pre-commit
          pre-commit run --all-files
          flutter test

      - name: Build the app
        run: |
          $version = python set-version.py | select-object -first 1
          flutter build windows --build-name=$version

      - name: Check generated files
        run: git diff -I '.*android.*flutter_plugins.*qrscanner_zxing' --exit-code

      - name: Move .dll files
        run: |
          $dest = "build\windows\x64\runner\Release"
          cp $dest\helper\_internal/MSVCP140.dll $dest\
          cp $dest\helper\_internal/VCRUNTIME140.dll $dest\
          cp $dest\helper\_internal/VCRUNTIME140_1.dll $dest\

      - name: Rename and archive app bundle
        run: |
          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          $dest = "deploy\yubioath-desktop-$branch-windows"
          mkdir $dest
          mv build\windows\x64\runner\Release\* $dest\
          mv resources\win\release-win.ps1 deploy
          mv resources\win\verify_dll.ps1 deploy
          mv resources deploy

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: yubioath-desktop-windows
          path: deploy

  sign-source:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Check tag format
      run: |
        if [[ "${GITHUB_REF}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
          echo "Tag matches format"
        else
          echo "Invalid tag format"
          exit 1
        fi

    - name: checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: yubioath-desktop-windows

    - name: docker login
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ghcr.io
        username: ci@yubico.com
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: write service account credentials
      env:
        GAC: ${{ secrets.SCRIBE_SA }}
      run: |
        echo "${GAC}" > scribe_sa.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/scribe/scribe_sa.json" >> $GITHUB_ENV

    - name: run scribe exe dll
      run: >
        docker run
        --user $(id -u):$(id -g)
        --volume $(pwd):/scribe
        --env-file <(env)
        ghcr.io/yubico/scribe-ci:v1
        --project-id scribe-prod-987134
        --bucket scribe-u-pub-yubioath-flutter-f94pro
        --config /scribe/.github/scribe-sign-exe-dll.yml
        submit .
        --synchronous
        --download-artifacts

    - name: unpack signed artifacts
      run: |
        mkdir -p signed
        mv scribe-download/*/sign-source/1.zip signed/
        rm -rf scribe-download
        cd signed
        unzip -j 1.zip || true
        rm 1.zip
        cd ..
        cp signed/authenticator-helper.exe yubioath-desktop-windows/*/helper/authenticator-helper.exe
        cp signed/authenticator.exe yubioath-desktop-windows/*/authenticator.exe
        cp signed/desktop_drop_plugin.dll yubioath-desktop-windows/*/desktop_drop_plugin.dll
        cp signed/flutter_windows.dll yubioath-desktop-windows/*/flutter_windows.dll
        cp signed/local_notifier_plugin.dll yubioath-desktop-windows/*/local_notifier_plugin.dll
        cp signed/screen_retriever_windows_plugin.dll yubioath-desktop-windows/*/screen_retriever_windows_plugin.dll
        cp signed/tray_manager_plugin.dll yubioath-desktop-windows/*/tray_manager_plugin.dll
        cp signed/url_launcher_windows_plugin.dll yubioath-desktop-windows/*/url_launcher_windows_plugin.dll
        cp signed/window_manager_plugin.dll yubioath-desktop-windows/*/window_manager_plugin.dll
        cp signed/dartjni.dll yubioath-desktop-windows/*/dartjni.dll
        cp signed/pythoncom314.dll yubioath-desktop-windows/*/helper/_internal/pywin32_system32/pythoncom314.dll
        cp signed/pywintypes314.dll yubioath-desktop-windows/*/helper/_internal/pywin32_system32/pywintypes314.dll

    - name: upload signed artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: signed-files
        path: yubioath-desktop-windows
        if-no-files-found: error
        compression-level: 0

  build-msi:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [sign-source]
    runs-on: windows-latest
    steps:
      - name: Check tag format
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
            echo "Tag matches format"
          else
            echo "Invalid tag format"
            exit 1
          fi

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download /signed dir
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Read variables from repo
        shell: bash
        run: cat .github/workflows/env >> $GITHUB_ENV

      - name: Create an unsigned .msi installer package
        run: |
          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          $env:PATH += ";$env:WIX\bin"
          $env:SRCDIR = "signed-files\yubioath-desktop-$branch-windows\"
          heat dir .\signed-files\yubioath-desktop-$branch-windows\ -out fragment.wxs -gg -scom -srd -sfrag -dr INSTALLDIR -cg ApplicationFiles -var env.SRCDIR
          candle .\fragment.wxs .\resources\win\yubioath-desktop.wxs -ext WixUtilExtension -arch x64
          light fragment.wixobj yubioath-desktop.wixobj -ext WixUIExtension -ext WixUtilExtension -o yubioath-desktop.msi

      - name: Rename and archive app bundle
        run: |
          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          $dest = "installer\yubioath-desktop-$branch-windows"
          mkdir installer
          mv yubioath-desktop.msi installer

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: installer
          path: installer

  sign-msi:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-msi]
    runs-on: ubuntu-latest
    steps:
    - name: Check tag
      run: |
        if [[ "${GITHUB_REF}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
          echo "Tag matches format"
        else
          echo "Invalid tag format"
          exit 1
        fi

    - name: checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

    - name: docker login
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ghcr.io
        username: ci@yubico.com
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: write service account credentials
      env:
        GAC: ${{ secrets.SCRIBE_SA }}
      run: |
        echo "${GAC}" > scribe_sa.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/scribe/scribe_sa.json" >> $GITHUB_ENV

    - name: run scribe msi
      run: >
        docker run
        --user $(id -u):$(id -g)
        --volume $(pwd):/scribe
        --env-file <(env)
        ghcr.io/yubico/scribe-ci:v1
        --project-id scribe-prod-987134
        --bucket scribe-u-pub-yubioath-flutter-f94pro
        --config /scribe/.github/scribe-sign-msi.yml
        submit .
        --synchronous
        --download-artifacts

    - name: unpack signed artifacts-msi
      run: |
        mkdir -p signed
        mv scribe-download/*/sign-source/1.zip signed/
        rm -rf scribe-download
        cd signed
        unzip -j 1.zip || true
        rm 1.zip
        cd ..

    - name: upload signed artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: signed-installer
        path: signed/*
        if-no-files-found: error
        compression-level: 0

  verify-signatures:
    needs: [sign-msi]
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: signed-files
          path: downloaded-artifact

      - name: Check for unsigned DLLs
        working-directory: .\downloaded-artifact
        run: .\verify_dll.ps1
